### ISSUE TITLE
Unexpected result when using `reverse=TRUE`

### ISSUE THREAD

**Issue by gowerc** [tagteam/prodlim#7]
Hey, Apologies in advance if this is a misunderstanding of the theory on my behalf but I am seeing some weird results when using `reverse=TRUE` to estimate the censoring distribution.  At least my expectation was that it would produce the same results as simply setting `event <- 1 - event` but I'm currently getting different results. 

Reproducible example:
```
library(dplyr)
library(prodlim)
library(survival)

n <- 60
set.seed(300)
## Using rounding to ensure some ties
idat <- tibble(
    times_real = round(rexp(n, 1 / 20)) + 1,
    cen = round(rexp(n, 1 / 40)) + 1,
    events = if_else(times_real <= cen, 1, 0),
    times = if_else(events == 1, times_real, cen)
)

## Using survfit
mod <- survfit(Surv(times, 1 - events) ~ 1, data = idat)

## Using reverse=TRUE option
pfit <- prodlim(Surv(times, events) ~ 1, data = idat, reverse = TRUE)
all(round(pfit$surv, 12) == round(mod$surv, 12))   # Does not match survfit

## Using 1-events as done for survfit
pfit <- prodlim(Surv(times, 1 - events) ~ 1, data = idat)
all(round(pfit$surv, 12) == round(mod$surv, 12))   #  Matches the same as survfit
```

**Comment by tagteam** [comment]
Hej Craig

exactly, this is the point of the reverse option and why I started the
prodlim package back in the days. in the case of ties between event and
censoring times, the reverse Kaplan-Meier for the censoring distribution
cannot be obtained with the survival package! when you observe the
minimum between T and C and there can be ties then one needs to define
what comes first in the case T=C. the convention in classical survival
analysis (see e.g., the PhD thesis of Richard Gill which you can get
from his homepage) is that T comes before C in this case and hence the formula for
the reverse Nelson-Aalen estimator at time t is

N_0(t)/(Y(t)-N_1(t))

where Y is the number at risk at time t, N_0 counts censoring events and
N_1 outcome events. in this way, prodlim makes sure that

S_n(t)*G_n(t) = P_n(min(T,C)>t)

where S_n, G_n are the normal and reverse Kaplan-Meier estimators and
P_n the empirical distribution function of the observed times.

cheers Thomas

Craig Gower-Page ***@***.***> writes:

> Hey, Apologies in advance if this is a misunderstanding of the theory
> on my behalf but I am seeing some weird results when using
> `reverse=TRUE` to estimate the censoring distribution.  At least my
> expectation was that it would produce the same results as simply
> setting `event <- 1 - event` but I'm currently getting different
> results.
>
> Reproducible example:
> ```
> library(dplyr)
> library(prodlim)
> library(survival)
>
> n <- 60
> set.seed(300)
> ## Using rounding to ensure some ties
> idat <- tibble(
>     times_real = round(rexp(n, 1 / 20)) + 1,
>     cen = round(rexp(n, 1 / 40)) + 1,
>     events = if_else(times_real <= cen, 1, 0),
>     times = if_else(events == 1, times_real, cen)
> )
>
> ## Using survfit
> mod <- survfit(Surv(times, 1 - events) ~ 1, data = idat)
>
> ## Using reverse=TRUE option
> pfit <- prodlim(Surv(times, events) ~ 1, data = idat, reverse = TRUE)
> all(round(pfit$surv, 12) == round(mod$surv, 12))   # Does not match survfit
>
> ## Using 1-events as done for survfit
> pfit <- prodlim(Surv(times, 1 - events) ~ 1, data = idat)
> all(round(pfit$surv, 12) == round(mod$surv, 12))   #  Matches the same as survfit
> ```

-- 
7LL-3 Time heals almost everything, give the time, some time.
